# Generated by Django 5.1 on 2024-08-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, unique=True)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=50)),
                ('phone_no', models.IntegerField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
